"""added workspace_members table

Revision ID: 143089b0e67b
Revises: e69bee30d0c1
Create Date: 2025-07-15 17:08:35.492488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143089b0e67b'
down_revision = 'e69bee30d0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workspace_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_members')
    # ### end Alembic commands ###
